config/routes.rb
Rails.application.routes.draw do
  resources :journals do
    resources :entries
  end

  root "journals#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :journal
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_journal, only: %i[new create show edit update destroy index]

  def new
    @entry = @journal.entries.build
  end

  def create
    @journal = Journal.find(params[:journal_id])
    @entry = @journal.entries.new(entry_params)


    respond_to do |format|
      if @entry.save
        format.turbo_stream
        format.html { redirect_to journal_entries_url(@journal, @entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @entry = @journal.entries.find(params[:id])
  end

  def update
    @entry = @journal.entries.find(params[:id])

    respond_to do |format|
      if @entry.update(entry_params)
        format.turbo_stream
        format.html { redirect_to journal_entries_url(@journal, @entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @journal = Journal.find(params[:journal_id])
    @entry = @journal.entries.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@entry) }
    end
  end

  private

  def set_journal
    @journal = Journal.find(params[:journal_id])
  end

  def entry_params
    params.require(:entry).permit(:text)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  def index
    @journals = Journal.all
    @journal = Journal.new
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.turbo_stream
        format.html { redirect_to journals_url(@journal), notice: "Journal was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.turbo_stream
        format.html { redirect_to journals_url(@journal), notice: "Journal was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @journal.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to journals_url, notice: "Journal was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  private

  def set_journal
    @journal = Journal.find(params[:id])
  end

  def journal_params
    params.require(:journal).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_entry.html.erb
<%= turbo_frame_tag entry do %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= entry.text %>
  </p>

  <% if action_name != "show" %>
    <%= button_to "Destroy this entry",journal_entry_path(@journal, entry), method: :delete,  class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"  %>
    <%= link_to 'Edit this entry', edit_journal_entry_path(@journal, entry), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
<% end %>

app/views/entries/_form.html.erb
<%= form_with(model: [@journal, @entry], class: "contents", id: "entry_form") do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% @entry.errors.each do |error| %>
          <li><%= entry.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :text %>
    <%= form.text_area :text, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/entries/create.turbo_stream.erb
<%= turbo_stream.prepend "entries" do %>
  <%= render @entry %>
<% end %>

<%= turbo_stream.replace "entry_form" do %>
  <%= render "form", journal: @journal.entries.build %>
<% end %>

app/views/entries/edit.html.erb
<%= turbo_frame_tag @entry do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing Entry</h1>

    <%= render "form", entry: @entry %>

    <%= link_to "Back to Journal", journal_entries_path(@journal), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/entries/index.html.erb
<div class="w-full">
  <div class="mx-auto md:w-2/3 w-full flex">
    <div class="mx-auto">
      <%= render @journal %>

      <%= link_to 'Back to journals', journals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Entries</h1>
    <%= turbo_frame_tag Entry.new do %>
      <%= link_to 'New Entry', new_journal_entry_path(@journal), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="entries" class="min-w-full">
    <%= render @journal.entries %>
  </div>
</div>

app/views/entries/new.html.erb
<!-- app/views/journals/new.html.erb -->

<h4>New Entry</h4>

<%= turbo_frame_tag @entry do %>
  <div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New journal</h1>

  <%= render "form", entry: @entry %>

  <%= link_to 'Back to Journals', journals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/entries/show.html.erb
<h1><%= @entry.text %></h1>
<p><%= @entry.created_at.strftime("Created on %m/%d/%Y at %I:%M%p") %></p>

<%= link_to "Edit Entry", edit_journal_entry_path(@journal, @entry) %>
<%= link_to "Delete Entry", journal_entry_path(@journal, @entry),data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
<%= link_to "Back to Journal", journal_path(@journal) %>

app/views/entries/update.turbo_stream.erb
<%= turbo_stream.update @entry do%>
  <%= render @entry %>
<% end %>

app/views/journals/_form.html.erb
<%= form_with(model: journal, class: "contents", id: "journal_form") do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/journals/_journal.html.erb
<%= turbo_frame_tag journal do %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= journal.name %>
  </p>

  <% if action_name != "show" %>
    <%= button_to "Destroy this journal",journal_path(journal), method: :delete,  class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"  %>
    <%= link_to "Show this journal", journal_entries_path(journal), data: { turbo_frame: "_top" }, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this journal', edit_journal_path(journal), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
<% end %>

app/views/journals/create.turbo_stream.erb
<%= turbo_stream.prepend "journals" do %>
  <%= render @journal %>
<% end %>

<%= turbo_stream.replace "journal_form" do %>
  <%= render "form", journal: Journal.new %>
<% end %>

app/views/journals/edit.html.erb
<%= turbo_frame_tag @journal do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing article</h1>

    <%= render "form", journal: @journal %>

    <%= link_to "Back to journals", journals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/journals/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Journals</h1>
    <%= turbo_frame_tag Journal.new do %>
      <%= link_to 'New Journal', new_journal_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="journals" class="min-w-full">
    <%= render @journals %>
  </div>
</div>

app/views/journals/new.html.erb
<!-- app/views/journals/new.html.erb -->

<h1>New Journal</h1>

<%= turbo_frame_tag @journal do %>
  <div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New journal</h1>

  <%= render "form", journal: @journal %>

  <%= link_to 'Back to articles', journals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/journals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @journal %>

    <%= link_to 'Back to journals', journals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/journals/update.turbo_stream.erb
<%= turbo_stream.update @journal do%>
  <%= render @journal %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalMicroservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>